:syntax enable
:set hlsearch
:set incsearch
:set tabstop=4
:set expandtab
:set cindent
:set shiftwidth=4
:set t_Co=256
:set confirm
:colorscheme jellybeans
:set number
:set cursorline
:set showcmd
:set cc=80

" Change tabstop to 2 for cpp files
autocmd Filetype cpp setlocal ts=2 sw=2 expandtab

set encoding=utf-8
set list listchars=tab:>-,trail:·

" To display vim-airline
:set laststatus=2

nnoremap , :mat Error "<C-R><C-W>"<CR>
let @o = ':browse confirm e'

" move lines
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Save file with Ctrl S
inoremap <C-S> <Esc>:w<CR>a

