#!/bin/bash

# Monitors battery level and notifies when it
# reach a certain value

currentEnergyFile=/sys/class/power_supply/BAT0/energy_now
maxEnergyFile=/sys/class/power_supply/BAT0/energy_full


function getCharge {
	current=$(cat ${currentEnergyFile})
	percentage=$(( ($current * 100) / $maxEnergy ))
}

maxEnergy=$(cat ${maxEnergyFile})
while (true)
do
	getCharge
	if [[ $1 -ge $percentage ]] ; then
		notify-send "Battery charge: $percentage"
	fi
	sleep 600
done


